# Generated by Django 3.0.4 on 2020-04-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200406_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='pics'),
        ),
    ]
